---
- name: Installing Wireguard
  become: true
  apt:
    name: wireguard
    state: present
  when: ansible_facts['os_family'] == "Debian"

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
- name: create server wireguard config
  vars_files:
    - roles/wireguard/vars/main.yml
  template:
    dest: /etc/wireguard/wg0.conf
    src: server_wg0.conf.j2
    owner: root
    group: root
    mode: '0600'

# https://docs.ansible.com/ansible/latest/collections/ansible/posix/sysctl_module.html
- name: enable and persist ip forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    sysctl_set: yes
    reload: yes
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_module.html

- name: start wireguard and enable on boot
  systemd:
    name: wg-quick@wg0
    enabled: yes
    state: started